name: Create Azure Resources

on:
  workflow_dispatch:
  push:
    paths:
      - 'ARM/**'
      - '.github/workflows/infraworkflow.yml'

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCEGROUP_NAME: ErZhao
  AZURE_WEBAPP_NAME: demo-webappsql-gh-actions-unique
  ASP_NAME: demo-webappsql-gh-actions
  SQLSERVER_NAME: demo-webappsql-gh-actions-srv
  DATABASE_NAME: demo-webappsql-gh-actions-db
  SQLADMIN_LOGIN: ${{ secrets.SQLADMIN_LOGIN }}
  SQLADMIN_PASS: ${{ secrets.SQLADMIN_PASS }}

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Azure Login with Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo
          
      - name: Deploy ARM Template resourcegroup
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: eastasia
          template: repo/templates/azuredeploy.resourcegroup.json
          parameters: repo/templates/azuredeploy.resourcegroup.parameters.json rgName=${{ env.AZURE_RESOURCEGROUP_NAME }}

      - name: Deploy ARM Template resources
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
